version: "3.9"
volumes:
  grafana-volume-1:
  prometheus-volume-1:

networks:
  grafana:
  metrics:
  database:

services:
  product-service:
    depends_on:
      - mariadb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    build: .
    ports:
      - "8080:8080"
    networks:
      - metrics
      - database
    command:
      - ':ProductService:run'

  mariadb:
    image: mariadb:10.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "spring"
      MYSQL_USER: "spring"
      MYSQL_PASSWORD: "spring"
    volumes:
      - ./ProductService/src/main/resources/init.sql:/data/application/init.sql

    command: --init-file /data/application/init.sql
    networks:
      database:

  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - ./resources/prometheus:/etc/prometheus
      - prometheus-volume-1:/prometheus
    networks:
      - metrics
      - grafana
    ports:
      - "9090:9090"
  grafana:
    ports:
      - "3000:3000"
    image: grafana/grafana:8.4.6
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    volumes:
      - grafana-volume-1:/var/lib/grafana
    networks:
      - grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    ports:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /dev/disk/:/dev/disk:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - metrics

  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    # Keep uncommented for windows - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
     # Keep uncommented for windows - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
     # Uncomment for running in vm - '--no-collector.powersupplyclass'
    expose:
      - "9100"
    networks:
      - metrics