version: "3.9"
services:
  api:
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M
    build: .
    ports:
      - "8080:8080"
    links:
      - prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ./src/main/resources:/etc/prometheus
    links:
      - grafana
  grafana:
    ports:
      - "3000:3000"
    image: grafana/grafana

  cadvisor:
    image: google/cadvisor
    links:
      - prometheus
    ports:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /dev/disk/:/dev/disk:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - "9100"
    links:
      - prometheus
