spring:
  application:
    # Name of the application (important for logging)
    name: ProductService
  mvc:
    # Deactivates logging of default exceptions which are handled by DefaultHandlerExceptionResolver
    log-resolved-exception: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: spring
    # use url jdbc:mariadb://localhost:3306/spring if docker is running local
    url: jdbc:mariadb://mariadb:3306/spring
    password: spring
  jpa:
    hibernate:
      #auto updates schema
      ddl-auto: update
      #recommended to deactivate according to spring logging
    open-in-view: false

#Activates Prometheus logging
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      #Adds tag for logging purposes
      application: ${spring.application.name}
