{
 "title": "Chaos Engineering - Sample Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "redis_instance",
    "label": "Redis Instance",
    "query": {
     "query": "label_values(redis_up, instance)"
    }
   },
   {
    "name": "docker_host",
    "label": "Docker Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$docker_host\"},name)"
    }
   },
   {
    "name": "job",
    "label": "Node Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Node Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "docker_project",
    "label": "Docker Project",
    "query": {
     "query": "label_values(container_label_com_docker_compose_project)"
    }
   },
   {
    "name": "resilience_instance",
    "label": "Resilience Instance",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state, instance)"
    }
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state, name)"
    }
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": {
     "query": "label_values(resilience4j_retry_calls_total, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Spring Boot Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "HTTP Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\",uri=~\"/api/.*\" }[1m])) by (status) >0 ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Node Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "CPU Basic",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "graph",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "trans {{device}} "
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "graph",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(rate(container_last_seen{name=~\".+\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 22, "x": 2, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$docker_host\",name=~\"$container\",name=~\".+\", container_label_com_docker_compose_project=~\"$docker_project\"}[5m])) by (name) *100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Received Network Traffic per Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic per Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage per Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Swap per Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_swap{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Remaining memory",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(100 - ((container_spec_memory_limit_bytes{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"} - container_memory_usage_bytes{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"})  * 100 / container_spec_memory_limit_bytes{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"}) ) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Usage memory",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "expr": "sum(container_spec_memory_limit_bytes{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"} - container_memory_usage_bytes{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"}) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Limit memory",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "expr": "sum(container_spec_memory_limit_bytes{name=~\".+\",container_label_com_docker_compose_project=~\"$docker_project\"}) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "( sum(100 * (redis_memory_used_bytes{instance=~\"$redis_instance\"}  / redis_memory_max_bytes{instance=~\"$redis_instance\"} )) or avg(100 * (redis_memory_used_bytes{instance=~\".+\"}  / redis_memory_max_bytes{instance=~\".+\"})))\r\n\r\n"
      }
     ]
    },
    {
     "title": "Clients",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "( sum(redis_connected_clients{instance=~\"$redis_instance\"}) or sum(redis_connected_clients{instance=~\".+\"}) ) "
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(max(max_over_time(redis_uptime_in_seconds{instance=~\"$redis_instance\"}[$__interval]))) or (max(max_over_time(redis_uptime_in_seconds{instance=~\".+\"}[$__interval]))) "
      }
     ]
    },
    {
     "title": "Commands Executed / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(redis_commands_processed_total{instance=~\"$redis_instance\"}[1m])) or sum(rate(redis_commands_processed_total{instance=~\".+\"}[1m])))\r\n\r\n\r\n\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Hits / Misses per Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(redis_keyspace_hits_total{instance=~\"$redis_instance\"}[5m])) or sum(irate(redis_keyspace_hits_total{instance=~\".+\"}[5m])))\r\n\r\n",
       "legendFormat": "hits"
      },
      {
       "expr": "(sum(irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])) or sum(irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])))\r\n\r\n",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "Command Calls / sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (cmd) (irate(redis_commands_total{instance=~\"$redis_instance\"} [1m])) or sum by (cmd) (irate(redis_commands_total{instance=~\".+\"} [1m]))))",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Total Items per DB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(sum (redis_db_keys{instance=~\"$redis_instance\"}) by (db) or sum (redis_db_keys{instance=~\".+\"}) by (db))",
       "legendFormat": "{{ db }} "
      }
     ]
    },
    {
     "title": "Expired / Evicted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(redis_expired_keys_total{instance=~\"$redis_instance\"}[5m]))  or sum(rate(redis_expired_keys_total{instance=~\".+\"}[5m])))",
       "legendFormat": "expired"
      },
      {
       "expr": "(sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) or sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])))",
       "legendFormat": "evicted"
      }
     ]
    },
    {
     "title": "Expiring vs Not-Expiring Keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum (redis_db_keys{instance=~\"$redis_instance\"}) - sum (redis_db_keys_expiring{instance=~\"$redis_instance\"}) or sum (redis_db_keys{instance=~\".+\"}) - sum (redis_db_keys_expiring{instance=~\".+\"}))",
       "legendFormat": "not expiring"
      },
      {
       "expr": "(sum (redis_db_keys_expiring{instance=~\"$instance\"}) or sum (redis_db_keys_expiring{instance=~\".+\"}))",
       "legendFormat": "expiring"
      }
     ]
    }
   ]
  },
  {
   "title": "Resilience4j",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CircuitBreaker States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Number" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_state{instance=~\"$resilience_instance\",application=~\"$application\"}",
       "legendFormat": "{{ name }}: {{ state }}"
      }
     ]
    },
    {
     "title": "Call rate: $circuitbreaker_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Calls/sec" }
     ],
     "targets": [
      {
       "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=~\"$resilience_instance\",name=~\"$circuitbreaker_name\",application=~\"$application\"}[1m])",
       "legendFormat": "{{ kind }} "
      },
      {
       "expr": "rate(resilience4j_circuitbreaker_calls_total{instance=~\"$resilience_instance\",name=~\"$circuitbreaker_name\",application=~\"$application\"}[1m])",
       "legendFormat": "{{ kind  }} "
      }
     ]
    },
    {
     "title": "Failure Rate: $circuitbreaker_name",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_failure_rate{instance=~\"$resilience_instance\",name=~\"$circuitbreaker_name\",application=~\"$application\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Rate retryable calls: $retry_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Number of calls" }
     ],
     "targets": [
      {
       "expr": "rate(resilience4j_retry_calls_total{application=~\"$application\",name=~\"$retry_name\"}[1m])",
       "legendFormat": "{{ kind }}"
      }
     ]
    }
   ]
  }
 ]
}